# core libraries are only included for supported host target triples
# core lib and the Rust compiler are distrubted together as a precompiled binary
# the core libraries are not included with our custom target
# cargo allows us to compile core and built-ins on demand using a config
[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

# the rust compiler assumes that certain functions are available for all systems
# some memory functions are not enabled by default e.g. memcpy, memset, memcmp
# compiler_builtins includes these functions rather than having to define them
# ourselves using name mangling (messy!)


# set default target arg for cargo for convenience
[build]
target = "x86_64-blog_os.json"
